version: '3.8' #which version of file format

services: #web and database services
  web:
    #build: . #build the web service from the dockerfile in current directory
    image: 491085418669.dkr.ecr.eu-west-2.amazonaws.com/flask-mysql2:latest
    ports:
      - "5002:5002"
    depends_on: #starts with db first as it depends on it
      - mydb2

  mydb2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw